### ISSUE TITLE
Installation on Notepad++ Portable

### ISSUE THREAD

**Issue by stoufa** [kurtmkurtm/HyperTheme-NotepadPlusPlus#1]
I tried both the `Data\themes` and the `App\DefaultData\themes` folders without luck.
The `%AppData%\Notepad++\themes` doesn't exist when using the [portable version of Notepad++](https://portableapps.com/apps/development/notepadpp_portable).
What to do in this case?
Thanks in advance.

**Comment by ghost** [comment]
I don't recall exactly where this is in the PortableApps version, but if memory serves, it's in App\Notepad++\themes\ (or wherever the programs' actual .exe is).

**Comment by stoufa** [comment]
Indeed! - For reference, I didn't find the `themes` folder, so, I created it and it works! 🎉
